# Generated by Django 4.1.6 on 2023-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cyber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=22)),
                ("surname", models.CharField(max_length=22)),
                ("email", models.EmailField(max_length=254)),
                ("coments", models.TextField()),
            ],
        ),
    ]
